export const RESORT = {
  name: 'Infinity Resort and Restaurant',
  shortName: 'Infinity Resort',
  tagline: 'Resort & Restaurant',
  address: {
    street: '732/1, Mandleshwar Road',
    area: 'Near New Era College',
    city: 'Mhow',
    state: 'Madhya Pradesh',
    country: 'India',
    full: '732/1, Mandleshwar Road, Near New Era College, Mhow, Madhya Pradesh, India',
  },
  phone: '+91 83590 55588',
  phoneRaw: '+918359055588',
  email: 'info@infinityresortandrestaurant.com',
  website: 'https://infinityresortandrestaurant.com',
  hours: '24/7',
  social: {
    facebook: 'https://www.facebook.com/infinityresortandrestaurant',
    instagram: 'https://www.instagram.com/infinityresortandrestaurant/',
  },
} as const;

export const IMAGES = {
  logo: '/images/branding/infinity-resort-logo.png',
  hero: {
    main: '/images/resort/hero-1.jpg',
    secondary: '/images/resort/hero-2.jpg',
    experiences: '/images/resort/services.jpg',
    attractions: '/images/resort/gallery-5.jpg',
  },
  rooms: [
    {
      id: 1,
      name: 'Standard Room',
      image: '/images/resort/room-standard.jpg',
      description: 'A comfortable and well-appointed room with all essential amenities for a pleasant stay.',
      bed: 'King Bed',
      view: 'Garden View',
      size: '280 sq ft',
      price: 0,
    },
    {
      id: 2,
      name: 'Deluxe Room',
      image: '/images/resort/room-deluxe.jpg',
      description: 'Spacious and elegantly designed room featuring premium furnishings and modern comforts.',
      bed: 'King Bed',
      view: 'Pool View',
      size: '350 sq ft',
      price: 0,
    },
    {
      id: 3,
      name: 'Superior Room',
      image: '/images/resort/accommodation.jpg',
      description: 'A refined room offering enhanced space, elegant decor and scenic views of the surroundings.',
      bed: 'King Bed',
      view: 'Nature View',
      size: '400 sq ft',
      price: 0,
    },
    {
      id: 4,
      name: 'Pearl Suite',
      image: '/images/resort/gallery-1.jpg',
      description: 'An luxurious suite with separate living area, premium amenities and panoramic views.',
      bed: 'King Bed',
      view: 'Panoramic',
      size: '550 sq ft',
      price: 0,
    },
  ],
  dining: {
    restaurant: '/images/resort/restaurant.jpg',
    food1: '/images/resort/gallery-3.jpg',
    food2: '/images/resort/gallery-4.jpg',
    food3: '/images/resort/gallery-6.jpg',
    bar: '/images/resort/pool.jpg',
  },
  experiences: [
    {
      id: 1,
      title: 'Infinity Pool',
      image: '/images/resort/pool.jpg',
      description: 'Take a dip in our stunning infinity pool with breathtaking views and tranquil waters.',
    },
    {
      id: 2,
      title: 'Fine Dining',
      image: '/images/resort/restaurant.jpg',
      description: 'Savour exquisite local and global cuisines prepared by our skilled culinary team.',
    },
    {
      id: 3,
      title: 'Poolside Dining',
      image: '/images/resort/gallery-2.jpg',
      description: 'Enjoy meals al fresco beside the pool with a refreshing and scenic ambiance.',
    },
    {
      id: 4,
      title: 'Event Lawn',
      image: '/images/resort/gallery-5.jpg',
      description: 'A lush green lawn perfect for celebrations, weddings and corporate gatherings.',
    },
    {
      id: 5,
      title: 'Wellness & Relaxation',
      image: '/images/resort/services.jpg',
      description: 'Unwind and rejuvenate in our peaceful surroundings designed for complete relaxation.',
    },
    {
      id: 6,
      title: 'Nature Trails',
      image: '/images/resort/gallery-7.jpg',
      description: 'Explore the natural beauty of Mhow with guided walks through scenic landscapes.',
    },
  ],
  attractions: [
    {
      id: 1,
      name: 'Patalpani Waterfall',
      image: '/images/resort/gallery-5.jpg',
      distance: '',
      description: 'A stunning waterfall cascading through lush green ravines, a must-visit natural wonder near Mhow.',
    },
    {
      id: 2,
      name: 'Mandu Fort',
      image: '/images/resort/gallery-7.jpg',
      distance: '',
      description: 'Explore the majestic ancient fort city with its breathtaking architecture and panoramic views.',
    },
    {
      id: 3,
      name: 'Omkareshwar',
      image: '/images/resort/gallery-1.jpg',
      distance: '',
      description: 'A sacred island town on the Narmada river, home to one of the 12 Jyotirlingas.',
    },
    {
      id: 4,
      name: 'Maheshwar',
      image: '/images/resort/gallery-6.jpg',
      distance: '',
      description: 'A historic town on the banks of the Narmada, known for its fort, temples and handloom weaving.',
    },
  ],
  gallery: [
    { id: 1, src: '/images/resort/hero-1.jpg', alt: 'Infinity Resort exterior', category: 'resort' },
    { id: 2, src: '/images/resort/room-standard.jpg', alt: 'Standard Room accommodation', category: 'rooms' },
    { id: 3, src: '/images/resort/restaurant.jpg', alt: 'Restaurant dining area', category: 'dining' },
    { id: 4, src: '/images/resort/pool.jpg', alt: 'Infinity swimming pool', category: 'amenities' },
    { id: 5, src: '/images/resort/gallery-1.jpg', alt: 'Resort architecture', category: 'resort' },
    { id: 6, src: '/images/resort/gallery-2.jpg', alt: 'Resort ambiance', category: 'resort' },
    { id: 7, src: '/images/resort/gallery-3.jpg', alt: 'Cuisine presentation', category: 'dining' },
    { id: 8, src: '/images/resort/gallery-4.jpg', alt: 'Resort surroundings', category: 'nature' },
    { id: 9, src: '/images/resort/room-deluxe.jpg', alt: 'Deluxe Room interior', category: 'rooms' },
    { id: 10, src: '/images/resort/gallery-5.jpg', alt: 'Event lawn area', category: 'amenities' },
    { id: 11, src: '/images/resort/gallery-6.jpg', alt: 'Resort landscape', category: 'nature' },
    { id: 12, src: '/images/resort/gallery-7.jpg', alt: 'Resort views', category: 'nature' },
  ],
  cta: '/images/resort/hero-2.jpg',
} as const;
